# -*- encoding: utf-8 -*-

{
    'name': 'Domex',
    'version': '1.0',
    'category': 'Custom',
    'description': """
Este es el módulo para la empresa Domex
""",
    'author': 'Rodrigo Fernandez',
    'website': 'http://solucionesprisma.com/',
    'depends': ['account','stock','mrp','sale_stock', 'purchase', 'report', 'orden_trabajo'],
    'data': [
        'data/report_paperformat_data.xml',
        'views/domex_view.xml',
        'views/report.xml',
        'views/reporte_invoice1.xml',
        'views/reporte_invoice2.xml',
        'views/reporte_invoice3.xml',
        'views/reporte_invoice4.xml',
        'views/reporte_voucher1.xml',
        'views/reporte_voucher2.xml',
        'views/reporte_voucher3.xml',
        'views/reporte_voucher4.xml',
        'views/reporte_voucher5.xml',
        'views/reporte_voucher6.xml',
        'views/reporte_voucher7.xml',
        'views/reporte_voucher8.xml',
        'views/reporte_voucher9.xml',
        'views/reporte_voucher10.xml',
        'views/reporte_voucher11.xml',
        'views/reporte_voucher12.xml',
        'views/reporte_voucher13.xml',
        'views/reporte_voucher14.xml',
        'views/reporte_voucher15.xml',
        'views/reporte_voucher16.xml',
        'views/reporte_voucher17.xml',
        'views/reporte_voucher18.xml',
        'views/reporte_voucher19.xml',
        'views/reporte_voucher20.xml',
        'views/reporte_voucher21.xml',
        'views/reporte_voucher22.xml',
        'views/reporte_voucher23.xml',
        'views/report_saleorder_domex.xml',
        'views/report_stockpicking_domex.xml',
        'views/report_saleordershipping_domex.xml',
        'views/report_purchaseordershipping_domex.xml',
        'views/account_payment_view.xml',
        'wizard/contrapartida_anticipo.xml',
        'security/domex_groups.xml',
        'security/domex_security.xml',
        'views/report_oc_importaciones_almex.xml',
        'views/report_oc_importaciones_domex.xml',
        'views/report_oc_importaciones_aplytek.xml',
        'views/report_so_almex.xml',
        'views/report_so_domex.xml',
        'views/report_so_aplytek.xml',
        'views/report_envio_almex.xml',
        'views/report_envio_domex.xml',
        'views/report_envio_aplytek.xml',
        'wizard/contrasenia_pago.xml',
        'wizard/purchase_order.xml',
        'views/contrasenias_pago.xml',
        'views/purchase_orders.xml',
        'wizard/cuentas_pagar_cobrar.xml',
        'views/cuentas_pagar_cobrar.xml',
        'wizard/libro_mayor_compras.xml',
        'views/libro_mayor_compras.xml',
        'views/report_orden_trabajo.xml',
        'views/product_template_views.xml',
        'views/stock_quant_views.xml',
    ],
    
    
    
    
    'demo': [],
    'installable': True
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
