# -*- encoding: utf-8 -*-

{
    'name': 'Domex',
    'version': '1.0',
    'category': 'Custom',
    'description': """
Este es el módulo para la empresa Domex
""",
    'author': 'Rodrigo Fernandez',
    'website': 'http://solucionesprisma.com/',
    'depends': ['account','stock','mrp','sale_stock'],
    'data': [
        'views/domex_view.xml',
        'views/report.xml',
        'views/reporte_invoice1.xml',
        'views/reporte_invoice2.xml',
        'views/reporte_invoice3.xml',
        'views/reporte_invoice4.xml',
        'views/reporte_voucher1.xml',
        'views/reporte_voucher2.xml',
        'views/reporte_voucher3.xml',
        'views/reporte_voucher4.xml',
        'views/reporte_voucher5.xml',
        'views/reporte_voucher6.xml',
        'views/reporte_voucher7.xml',
        'views/reporte_voucher8.xml',
        'views/reporte_voucher9.xml',
        'views/reporte_voucher10.xml',
        'views/reporte_voucher11.xml',
        'views/reporte_voucher12.xml',
        'views/reporte_voucher13.xml',
        'views/reporte_voucher14.xml',
        'views/reporte_voucher15.xml',
        'views/reporte_voucher16.xml',
        'views/reporte_voucher17.xml',
        'views/reporte_voucher18.xml',
        'views/reporte_voucher19.xml',
        'views/reporte_voucher20.xml',
        'views/reporte_voucher21.xml',
        'views/reporte_voucher22.xml',
        'views/report_saleorder_domex.xml',
        'views/report_stockpicking_domex.xml',
        'views/report_saleordershipping_domex.xml',
        'views/account_payment_view.xml',
        'wizard/contrapartida_anticipo.xml',
    ],
    'demo': [],
    'installable': True
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
